handleError: forgot to specify the context error handler call. credentialsLoad: handle failure to retrieve credentials from gConf by returning null so the application gets notified.